### ISSUE TITLE
is a new flask app created when running `celery worker -A celery_worker.celery`?

### ISSUE THREAD

**Issue by royling** [miguelgrinberg/flasky-with-celery#15]
I am new to Python and Flask/Celery, thanks for the great example, but I just cannot understand how this works, so here's my dumb question:

I can see `create_app` is invoked both when [starting flask app via `python manage.py`](https://github.com/miguelgrinberg/flasky-with-celery/blob/master/manage.py#L21) and [starting celery worker via `celery worker -A celery_worker.celery`](https://github.com/miguelgrinberg/flasky-with-celery/blob/master/celery_worker.py#L5)

does this mean actually there're two `Flask` instances created?

**Comment by miguelgrinberg** [comment]
Yes, each process has its own Flask app instance. The Celery workers do not run a web server through, the app in those processes is there to support any extensions that require an app context to access app resources such as configuration.

**Comment by royling** [comment]
That's my initial guess, and thank you for quick reply and clarification.
