### ISSUE TITLE
Daemonize using systemd

### ISSUE THREAD

**Issue by mocaccano** [miguelgrinberg/flasky-with-celery#24]
Hi Miguel,
I'm trying to daemonize the celery worker in my flask application. I'm following the Celery documentation [here](https://docs.celeryproject.org/en/stable/userguide/daemonizing.html#usage-systemd).
The guide says to use `'${CELERY_BIN} -A $CELERY_APP multi start ` while till now I've been starting the Celery worker server in the foreground using  `celery -A worker.celery worker ...`
I'd like to follow the guide because it also specifies the actions for stopping and reloading the service. In any case, with multi start, I get an error when the worker tries to create its instance of the flask app:
```
app = create_app()
app.app_context().push
```
Could you please help with this? Thanks

**Comment by miguelgrinberg** [comment]
Without the error, I can't really tell you much. Also, what's the value of `$CELERY_APP` and `$CELERY_BIN`?

**Comment by mocaccano** [comment]
Actually, it works now! I was trying to get you the logs of the error, and then turns out even the normal foreground launch was not working. Earlier in the day we'd daemonized the flask server itself, and I think that changed the owner of the log files. I had to do `chown uname:uname logs/server.log` and after that everything's good.

To answer your question:

```
CELERY_BIN="/home/uname/ufolder/urepo/env/bin/celery"
CELERY_APP="worker.celeri"
```

Thanks for the quick response!

**Comment by miguelgrinberg** [comment]
Great, glad this is working now.
