### ISSUE TITLE
Using Flask-SQLAlchemy inside celery task 

### ISSUE THREAD

**Issue by xh4vm** [miguelgrinberg/flasky-with-celery#25]
Hello!
I am very sorry, but I ran into a problem (it was discussed earlier, for example https://github.com/miguelgrinberg/flasky-with-celery/issues/12#issue-357748476). Can't access database data from a celery task. 

_app/\_\_init\_\_.py_
```
from celery import Celery
from config import Config
from .extensions.flask_elastic import FlaskElastic
from flask_migrate import Migrate
import os
from .db import db


migrate = Migrate()
celery = Celery(__name__, backend=Config.CELERY_RESULT_BACKEND, broker=Config.CELERY_BROKER_URL)

def create_app(config_class=Config):
    app = FlaskElastic(__name__, config_class=config_class)

    db.init_app(app)
    migrate.init_app(app, db)

    register_blueprints(app)

    app.app_context().push()

    return app
    

def make_celery(app):
    celery = Celery(
        app.import_name,
        backend=app.config['CELERY_RESULT_BACKEND'],
        broker=app.config['CELERY_BROKER_URL']
    )
    celery.conf.update(app.config)

    class ContextTask(celery.Task):
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return self.run(*args, **kwargs)

    celery.Task = ContextTask
    return celery
```

_tasks.py_
```
from flask import current_app
from app import celery 


@celery.task
def get_hashes():
    with current_app.app_context():
        return Hash.query.all()
```

The task succeeds, but no objects are returned. Thanks very much.

**Comment by miguelgrinberg** [comment]
You can't use `current_app` to create an app context, because this variable is only defined when an app context is already defined. Use a real app instance to create your context.

**Comment by xh4vm** [comment]
Thanks for your reply! Sorry, but the output of the database contents from the task Celery is empty anyway. 

_tasks.py_
```
from app import create_app, celery 


@celery.task
def get_hashes():
    app = create_app()
    with app.app_context():
        return Hash.query.all()
```

**Comment by miguelgrinberg** [comment]
@xh4vm I'm not sure how I can help. If the application instance that you are using to create the app context is correctly configure with the database, then this should work. If it doesn't and you think this is a bug in either Celery, Flask or Flask-SQAlchemy, then the bug should be reported to the project owners, though I doubt that very much.

**Comment by xh4vm** [comment]
I'm sorry it was my mistake. Everything really works!
