### ISSUE TITLE
Remote celery worker and database communication in microservices

### ISSUE THREAD

**Issue by voqtuyen** [miguelgrinberg/flasky-with-celery#26]
Hi Miguel,

Thanks for sharing the content of micro_* repositories and this celery repository. 
In my current situation, I have a system like this:

![](https://i.stack.imgur.com/vruvI.jpg)

In this case, the celery worker will be located remotely and only here the code for tasks will be defined. The users service just need to send the task via redis `celery.send_task('add', args=[param1, param2])`

The problem is that I need to get the result of the task on completion and persist it to users database. 

From your repo, I can think about one solution is to allow remote celery worker to connect to the users database and update the result when it's completed using Flask-SQLAlchemy. I am confused here about if I need to copy the users db model to worker repository or any solution other than copying.

**Comment by miguelgrinberg** [comment]
Your Celery worker must send a request to the user service to update the database. You would definitely don't want a database or model definitions to be shared across microservices.

**Comment by voqtuyen** [comment]
Thanks. I actually first think about this idea when it comes to scaling the workers.

1. As my understanding, the way we access to task result on the producer side using result backend is like this:
`task = long_task.AsyncResult(task_id)`
So in order to get the result on the producer side, we need to keep tracks of the task_ids and have to poll for task statuses and update to database on success.

2. Could you please give some ways to achieve this `Your Celery worker must send a request to the user service to update the database`?. Is there any way like callbacks to asynchronously update the user database when the task is executed successfully by celery worker.

**Comment by miguelgrinberg** [comment]
I'm sorry but I don't understand your point 1. You never mentioned the need to access the task result before. Why do you need to get the result? I thought all you needed was to update your user database with this result.

Regarding point 2, you are looking at this in the wrong way. You have a users microservice that accepts HTTP requests, correct? Your Celery task can send an HTTP request to the users microservice with the change that needs to be made to the database.

**Comment by voqtuyen** [comment]
Yes it's correct.
> I thought all you needed was to update your user database with this result


Because users microservice requires token authentication, thus from remote celery workers I can not make HTTP requests to update users database.

Because of that, what I mean for point 1 is that I try to get the task result inside users service and update it to users database.

**Comment by miguelgrinberg** [comment]
You should provision a token that the Celery worker can use to make calls into the users service.

**Comment by voqtuyen** [comment]
Thanks for your sharing. I close the issue now
