### ISSUE TITLE
Real time processing 

### ISSUE THREAD

**Issue by raedatoui** [miguelgrinberg/flasky-with-celery#9]
Hello
I have a general question about where the real time processing code from the Celery docs would live in this structure.
http://docs.celeryproject.org/en/latest/userguide/monitoring.html#real-time-processing
It tried adding those event handlers in the worker and in the main app, and in both instances, things get stuck due to this line ` recv.capture(limit=None, timeout=None, wakeup=True)`
I might be missing something fundamental. Any advice would be greatly appreciated!

**Comment by miguelgrinberg** [comment]
This goes in the main app, or else it can also go in a standalone script that is separate from the app and from the workers. The idea is that anything that happens in the cluster of workers is reported to this Receiver object as an event.

The docs aren't very clear on this, but my guess is that the call to `recv.capture` does not return, it just stays busy processing events from the cluster. So if you put this on your main app, you'll have to use a background thread to prevent the app from blocking.

**Comment by raedatoui** [comment]
that makes sense and explains the lockup. thanks for your help!
